config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :menus
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :order_items
	has_one_attached :image

  validates :title, :price, :image, presence: true
  validates :title, length: { minimum: 4 }
  validates :price, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]


  # GET /menus or /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:title, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/home/index.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Welcome</h1>
        <p class="lead text-muted">We are glad to see you in our coffee shop.</p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @menus.each do |menu| %>
          <div class="col">
            <div class="card shadow-sm">
              <image src="<%=(url_for(menu.image.variant(resize_to_limit: [300, 300])))%>">

              <div class="card-body">
                <p class="card-text">Title: <%= menu.title %></p>
                <p class="card-text">Price: <%= menu.price %>$</p>
 
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Order it</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        </div>
    </div>
  </div>

</main>

app/views/layouts/_footer.html.erb
<footer class="text-muted py-5">
<div class="container">
  <p class="float-end mb-1">
    <a href="#" class="btn btn-dark bi bi-arrow-up-circle-fill"></a>
  </p>
  <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
  <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="p-3 mb-3 border-bottom bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <%= link_to 'Cava', root_path, class:"navbar-brand bi bi-cup-fill", style:"color: white"%>
          <% if user_signed_in? %>
            <div class="dropdown text-end">
              <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
              </a>
              <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                <li><%= link_to "Edit Profile", edit_user_registration_path, class:"dropdown-item" %></li>
                <%= link_to "Cart", menus_path, class:"dropdown-item" %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, class:"dropdown-item" %></li>
              </ul>
            </div>
          <% else %>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <%= link_to "Log in", new_user_session_path, type:"button", class:"nav-link px-2 link-light" %>
          <%= link_to "Sign up", new_user_registration_path, type:"button", class:"nav-link px-2 link-light" %>
        </ul>
      <% end %>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CavaShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", defer: true %>
    <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="field form-group">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :image, style: "display: block" %>
      <%= form.file_field :image, class:"form-control" %>
    </div>
    <br>
    <div>
      <%= form.submit class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div class="col">
  <div class="card shadow-sm">
    <image src="<%=(url_for(menu.image.variant(resize_to_limit: [300, 300])))%>">

    <div class="card-body">
      <p class="card-text">Title: <%= menu.title %></p>
      <p class="card-text">Price: <%= menu.price %>$</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", menu, class:"btn btn-sm btn-outline-secondary" %> 
        </div>
          <small class="text-muted">9 mins</small>
      </div>
    </div>
  </div>
</div>

app/views/menus/edit.html.erb
<div class="py-5 text-center container">
  <h1>Editing menu</h1>
</div>

<%= render "form", menu: @menu %>

<br>

<div class="py-5 text-center container">
  <%= link_to "Show this menu", @menu, class:"btn btn-warning btn-sm" %> |
  <%= link_to "Back to menus", menus_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/menus/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="py-5 text-center container">
  <h1>Menus</h1>
  <%= link_to "New product", new_menu_path, class:"btn btn-secondary" %>
</div>

<div id="menus">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @menus.each do |menu| %>
          <%= render menu %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/menus/new.html.erb
<div class="py-5 text-center container">
  <h1>New menu</h1>
</div>

<%= render "form", menu: @menu %>

<br>

<div class="py-5 text-center container">
  <%= link_to "Back to menu", menus_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/menus/show.html.erb
<p style="color: green"><%= notice %></p>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <%= render @menu %>
      </div>
    </div>
  </div>

<div class="py-5 text-center container">
  <%= link_to "Edit this menu", edit_menu_path(@menu), class:"btn btn-secondary btn-sm" %> |
  <%= link_to "Back to menus", menus_path, class:"btn btn-dark btn-sm" %>
  <br><br>
  <%= button_to "Destroy this menu", @menu, method: :delete, class:"btn btn-danger btn-sm" %>
</div>